service: serverless-graphql-client

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  stage: production
  region: us-east-1

plugins:
  - serverless-finch

custom:
  client:
    bucketName: s3-foundobjx-serverless1-graphql
    distributionFolder: build
